global using Ardalis.Result;
global using Ardalis.Result.FluentValidation;
global using FluentValidation;
global using LiteBus.Commands.Abstractions;
global using LiteBus.Queries.Abstractions;
global using Mapster;
global using Microsoft.Extensions.Logging;
global using ShopFinance.Domain.Common.Base;
global using ShopFinance.Domain.Common.Interfaces;
